#!/usr/bin/env python3
"""Export apply.py's answer rules for the browser filler (ashby_fill.user.js / bookmarklet).
The applicant's email, phone and street address are written as {{email}} / {{phone}} / {{street}} placeholders: the
browser fills them from the applicant's own one-time setup, so they never appear in this (public) repository.
usage: python3 export_rules.py <profile.json> <answers.json> > rules.js"""
import re, json, sys, os, datetime, time
HERE = os.path.dirname(os.path.abspath(__file__)); TOOLS = os.path.join(os.path.dirname(HERE), "tools")
SECRET = ("email", "phone", "street")
prof = json.load(open(sys.argv[1])); ans = json.load(open(sys.argv[2]))
P = {k: ("{{%s}}" % k if k in SECRET else v) for k, v in prof.items()}
src = open(os.path.join(TOOLS, "apply.py")).read()
g = {"re": re, "json": json, "datetime": datetime, "os": os, "time": time, "P": P, "ANS": ans, "date": datetime.date,
     "JOB_CHOICE_RULES": [], "JOB_TEXT_RULES": [], "JOB_WHY": "", "__builtins__": __builtins__}
exec(src[src.index("first,last="):src.index("\n", src.index("first,last="))], g)
exec(src[src.index("TEXT_RULES=["):src.index("\n]\n", src.index("CHOICE_RULES=[")) + 3], g)
for name in ("PERSONAL_Q=", "TECH_Q=", "TECH_BANK=", "TECH_DEFAULT=", "NOT_MINE=", "STACK_TRUE=", "ENV_TRUE=", "OPTION_TRUE=", "NEVER_APPLY=", "HEAR_BAD=", "HEAR_Q="):
    i = src.index("\n" + name) + 1; exec(src[i:src.index("\n", i)], g)
i = src.index("WHY_BY_CAT={"); exec(src[i:src.index("\n}\n", i) + 3], g)
sys.path.insert(0, TOOLS); import cover
g["CATS"], g["PARA"] = cover.CATS, cover.PARA
TODAY = {datetime.date.today().strftime("%m/%d/%y"), time.strftime("%m/%d/%y")}

def jsre(p):
    """Python regex -> JavaScript regex source (the patterns use a common subset)."""
    if isinstance(p, re.Pattern): p = p.pattern
    q = p.replace("(?P<", "(?<").replace("\\Z", "$").replace("\\A", "^")
    q = re.sub(r"\(\?P=(\w+)\)", r"\\k<\1>", q)
    if "(?i)" in q: q = q.replace("(?i)", "")
    return q
def val(v):
    if isinstance(v, str):
        return "{{today}}" if v in TODAY else v
    if isinstance(v, (list, tuple)): return [val(x) for x in v]
    return v
flags = lambda r: "i" if isinstance(r, re.Pattern) and r.flags & re.I else ""
out = {
    "TEXT_RULES": [[jsre(p), val(v)] for p, v in g["TEXT_RULES"]],
    "CHOICE_RULES": [[jsre(p), val(v)] for p, v in g["CHOICE_RULES"]],
    "PERSONAL_Q": [jsre(g["PERSONAL_Q"]), flags(g["PERSONAL_Q"])], "TECH_Q": [jsre(g["TECH_Q"]), flags(g["TECH_Q"])],
    "NOT_MINE": [jsre(g["NOT_MINE"]), flags(g["NOT_MINE"])],
    "TECH_BANK": [[jsre(p), v] for p, v in g["TECH_BANK"]], "TECH_DEFAULT": g["TECH_DEFAULT"],
    "STACK_TRUE": jsre(g["STACK_TRUE"]), "ENV_TRUE": jsre(g["ENV_TRUE"]), "OPTION_TRUE": jsre(g["OPTION_TRUE"]),
    "NEVER_APPLY": jsre(g["NEVER_APPLY"]), "HEAR_BAD": jsre(g["HEAR_BAD"]), "HEAR_Q": jsre(g["HEAR_Q"]),
    "WHY_BY_CAT": g["WHY_BY_CAT"], "CATS": [[c, jsre(p)] for c, p in g["CATS"]], "PARA": g["PARA"],
    "WHY_US": ans.get("why_us", ""),
    "PROFILE": {k: v for k, v in P.items() if k not in ("resume", "cover_letter")},
    "EXPORTED": time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime()),
}
blob = json.dumps(out, ensure_ascii=False)
for k in SECRET:   # nothing private may leave this machine
    if prof.get(k) and prof[k] in blob: sys.exit(f"refusing: the {k} value would be exported")
print("/* generated by job-search/ashby_fill/export_rules.py from tools/apply.py; do not edit */")
print("const AKF_RULES = " + blob + ";")
